services:
  api:
    build: .
    container_name: fastapi-pedidos-api
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: pedidos-criados
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F
      RABBITMQ_QUEUE: pedidos-criados
      MONGO_URL: mongodb://mongo:27017
    depends_on:
      - zookeeper
      - kafka
      - rabbitmq
      - mongo

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: fastapi-pedidos-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: fastapi-pedidos-kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: fastapi-pedidos-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: mongo:latest
    container_name: fastapi-pedidos-mongo
    ports:
      - "27017:27017"